-- ==============================================================================
-- Hartonomous Database Schema
-- ==============================================================================
--
-- This schema implements a content-addressable geometric database for storing
-- text data as 4D spatial structures.
--
-- Core Concepts:
--   - Atoms: Individual Unicode codepoints as 4D points on S³ (indivisible)
--   - Compositions: Sequences of atoms (n-grams) as 4D linestrings
--   - AtomComposition: Join table maintaining sequence order
--
-- Key Properties:
--   - Content-addressable: SAME CONTENT = SAME HASH = SAME RECORD
--   - Spatial indexing: Hilbert curve indices for fast nearest-neighbor queries
--   - Geometric queries: Find similar compositions via 4D distance
--   - Deduplication: Automatic via hash-based primary keys
--
-- ==============================================================================

-- Enable required extensions

-- ==============================================================================
-- SAMPLE DATA (for testing)
-- ==============================================================================

-- Insert sample atoms (letters 'a', 'b', 'c')
-- Note: In production, these would be generated by the C++ engine

-- Example: Atom for 'a' (codepoint 97)
-- INSERT INTO atoms (hash, codepoint, s3_x, s3_y, s3_z, s3_w, ...)
-- VALUES (...);

-- ==============================================================================
-- GRANTS (adjust for your security model)
-- ==============================================================================

-- GRANT SELECT, INSERT ON atoms TO app_user;
-- GRANT SELECT, INSERT ON compositions TO app_user;
-- GRANT SELECT, INSERT ON atom_compositions TO app_user;
