version: '3.8'

services:
  postgres-staging:
    profiles:
      - staging
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_staging
      POSTGRES_DB: hartonomous_staging
