version: '3.8'

services:
  postgres-localhost:
    profiles:
      - localhost
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_local
      POSTGRES_DB: hartonomous_localhost
