./scripts/linux/01-build.sh -c -T -i > build-log.txt 2>&1;
./scripts/linux/02-install.sh > install-log.txt 2>&1;
sudo ldconfig > ldconfig-log.txt 2>&1;
./scripts/linux/03-setup-database.sh --drop > setup-database-log.txt 2>&1;
./UCDIngestor/setup_db.sh > ucd-setup-db-log.txt 2>&1;
./scripts/linux/04_run_ingestion.sh > run-ingestion-log.txt 2>&1;
./scripts/linux/05-seed-unicode.sh > seed-unicode-log.txt 2>&1;
./scripts/linux/20-ingest-mini-lm.sh > ingest-minilm-log.txt 2>&1;
./scripts/linux/30-ingest-text.sh > ingest-text-log.txt 2>&1;
./scripts/linux/40-run-queries.sh > run-queries-log.txt 2>&1;
./build/linux-release-max-perf/Engine/tools/walk_test > walk-test-log.txt 2>&1;