CREATE TABLE IF NOT EXISTS hartonomous.RelationRating (
    RelationId UUID PRIMARY KEY REFERENCES hartonomous.Relation(Id) ON DELETE CASCADE,
    Observations UINT64 DEFAULT 1 NOT NULL,
    RatingValue DOUBLE PRECISION NOT NULL DEFAULT 1000,
    KFactor DOUBLE PRECISION DEFAULT 1.0 NOT NULL,
    CreatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    ModifiedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    ValidatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_RelationRating_RatingValue ON hartonomous.RelationRating(RatingValue);
