CREATE TABLE IF NOT EXISTS hartonomous.RelationEvidence (
    Id UUID PRIMARY KEY,
    ContentId UUID NOT NULL REFERENCES hartonomous.Content(Id) ON DELETE CASCADE,
    RelationId UUID NOT NULL REFERENCES hartonomous.Relation(Id) ON DELETE CASCADE,
    IsValid BOOLEAN DEFAULT TRUE NOT NULL,
    SourceRating DOUBLE PRECISION NOT NULL DEFAULT 1000,
    SignalStrength DOUBLE PRECISION NOT NULL DEFAULT 1.0 CHECK (SignalStrength BETWEEN 0 AND 1),
    CreatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    ModifiedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    ValidatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
