// <auto-generated />
using System;
using System.Collections.Generic;
using Hartonomous.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hartonomous.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251206060825_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BPETokenConstant", b =>
                {
                    b.Property<Guid>("ComposingTokensId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConstantsId")
                        .HasColumnType("uuid");

                    b.HasKey("ComposingTokensId", "ConstantsId");

                    b.HasIndex("ConstantsId", "ComposingTokensId")
                        .IsUnique()
                        .HasDatabaseName("uq_constant_tokens");

                    b.ToTable("constant_tokens", (string)null);
                });

            modelBuilder.Entity("Hartonomous.Core.Domain.Entities.BPEToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<LineString>("CompositionGeometry")
                        .HasColumnType("geometry(LineStringZM, 4326)")
                        .HasColumnName("composition_geometry");

                    b.Property<double>("CompressionRatio")
                        .HasColumnType("double precision");

                    b.PrimitiveCollection<List<Guid>>("ConstantSequence")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("constant_sequence");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("deleted_by");

                    b.Property<long>("Frequency")
                        .HasColumnType("bigint")
                        .HasColumnName("frequency");

                    b.Property<byte[]>("Hash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("hash");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<int>("MergeLevel")
                        .HasColumnType("integer")
                        .HasColumnName("merge_level");

                    b.PrimitiveCollection<List<int>>("ParentTokenIds")
                        .HasColumnType("integer[]");

                    b.Property<double?>("PathLength")
                        .HasPrecision(18, 6)
                        .HasColumnType("double precision")
                        .HasColumnName("path_length");

                    b.Property<int>("SequenceLength")
                        .HasColumnType("integer")
                        .HasColumnName("sequence_length");

                    b.Property<int>("TokenId")
                        .HasColumnType("integer")
                        .HasColumnName("token_id");

                    b.Property<int>("TotalSize")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.Property<long>("VocabularyRank")
                        .HasColumnType("bigint")
                        .HasColumnName("vocabulary_rank");

                    b.HasKey("Id");

                    b.HasIndex("CompositionGeometry")
                        .HasDatabaseName("ix_bpe_tokens_composition_gist")
                        .HasFilter("composition_geometry IS NOT NULL");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("CompositionGeometry"), "gist");

                    b.HasIndex("Frequency")
                        .HasDatabaseName("ix_bpe_tokens_frequency");

                    b.HasIndex("Hash")
                        .IsUnique()
                        .HasDatabaseName("ix_bpe_tokens_hash");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_bpe_tokens_is_active");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_bpe_tokens_is_deleted");

                    b.HasIndex("LastUsedAt")
                        .HasDatabaseName("ix_bpe_tokens_last_used");

                    b.HasIndex("MergeLevel")
                        .HasDatabaseName("ix_bpe_tokens_merge_level");

                    b.HasIndex("PathLength")
                        .HasDatabaseName("ix_bpe_tokens_path_length")
                        .HasFilter("path_length IS NOT NULL");

                    b.HasIndex("SequenceLength")
                        .HasDatabaseName("ix_bpe_tokens_sequence_length");

                    b.HasIndex("TokenId")
                        .IsUnique()
                        .HasDatabaseName("ix_bpe_tokens_token_id");

                    b.HasIndex("VocabularyRank")
                        .HasDatabaseName("ix_bpe_tokens_vocabulary_rank");

                    b.HasIndex("IsActive", "Frequency", "IsDeleted")
                        .HasDatabaseName("ix_bpe_tokens_active_frequency_deleted");

                    b.HasIndex("MergeLevel", "SequenceLength", "IsDeleted")
                        .HasDatabaseName("ix_bpe_tokens_merge_sequence_deleted");

                    b.ToTable("bpe_tokens", (string)null);
                });

            modelBuilder.Entity("Hartonomous.Core.Domain.Entities.Constant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ActivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activated_at");

                    b.Property<Guid?>("CanonicalConstantId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("data");

                    b.Property<DateTime?>("DeduplicatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deduplicated_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("deleted_by");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Frequency")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("frequency");

                    b.Property<byte[]>("Hash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea")
                        .HasColumnName("hash");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsDuplicate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_duplicate");

                    b.Property<Guid?>("LandmarkId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastAccessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_accessed_at");

                    b.Property<Point>("Location")
                        .HasColumnType("geometry(PointZM, 4326)")
                        .HasColumnName("location")
                        .HasComment("Materialized POINTZM view: X=spatial, Y=entropy, Z=compressibility, M=connectivity");

                    b.Property<DateTime?>("ProjectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("projected_at");

                    b.Property<long>("ReferenceCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("reference_count");

                    b.Property<int>("Size")
                        .HasColumnType("integer")
                        .HasColumnName("size");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("updated_by");

                    b.Property<Guid?>("canonical_constant_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ContentType")
                        .HasDatabaseName("ix_constants_content_type");

                    b.HasIndex("Frequency")
                        .HasDatabaseName("ix_constants_frequency_hot")
                        .HasFilter("frequency > 0.001");

                    b.HasIndex("Hash")
                        .IsUnique()
                        .HasDatabaseName("uq_constants_hash");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_constants_is_deleted")
                        .HasFilter("is_deleted = false");

                    b.HasIndex("IsDuplicate")
                        .HasDatabaseName("ix_constants_is_duplicate")
                        .HasFilter("is_duplicate = true");

                    b.HasIndex("LandmarkId");

                    b.HasIndex("LastAccessedAt")
                        .HasDatabaseName("ix_constants_last_accessed_recent");

                    b.HasIndex("Location")
                        .HasDatabaseName("ix_constants_location_gist");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.HasIndex("Size")
                        .HasDatabaseName("ix_constants_size");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_constants_status");

                    b.HasIndex("canonical_constant_id");

                    b.ToTable("constants", (string)null);
                });

            modelBuilder.Entity("Hartonomous.Core.Domain.Entities.ContentBoundary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AtomCount")
                        .HasColumnType("integer")
                        .HasColumnName("atom_count");

                    b.Property<double>("BoundaryArea")
                        .HasPrecision(18, 6)
                        .HasColumnType("double precision")
                        .HasColumnName("boundary_area");

                    b.Property<Polygon>("BoundaryGeometry")
                        .IsRequired()
                        .HasColumnType("geometry(PolygonZM, 4326)")
                        .HasColumnName("boundary_geometry");

                    b.Property<double>("BoundaryPerimeter")
                        .HasPrecision(18, 6)
                        .HasColumnType("double precision")
                        .HasColumnName("boundary_perimeter");

                    b.Property<Point>("Centroid")
                        .IsRequired()
                        .HasColumnType("geometry(PointZM, 4326)")
                        .HasColumnName("centroid");

                    b.Property<string>("ComputationMethod")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("ConvexHull")
                        .HasColumnName("computation_method");

                    b.Property<DateTime>("ComputedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("computed_at");

                    b.Property<Guid>("ContentIngestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("content_ingestion_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("deleted_by");

                    b.Property<double>("Density")
                        .HasPrecision(18, 6)
                        .HasColumnType("double precision")
                        .HasColumnName("density");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("AtomCount")
                        .HasDatabaseName("ix_content_boundaries_atom_count");

                    b.HasIndex("BoundaryArea")
                        .HasDatabaseName("ix_content_boundaries_area");

                    b.HasIndex("BoundaryGeometry")
                        .HasDatabaseName("ix_content_boundaries_geometry_gist");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("BoundaryGeometry"), "gist");

                    b.HasIndex("Centroid")
                        .HasDatabaseName("ix_content_boundaries_centroid_gist");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Centroid"), "gist");

                    b.HasIndex("ComputationMethod")
                        .HasDatabaseName("ix_content_boundaries_method");

                    b.HasIndex("ComputedAt")
                        .HasDatabaseName("ix_content_boundaries_computed_at");

                    b.HasIndex("ContentIngestionId")
                        .IsUnique()
                        .HasDatabaseName("ix_content_boundaries_content_ingestion_id");

                    b.HasIndex("Density")
                        .HasDatabaseName("ix_content_boundaries_density");

                    b.HasIndex("ComputationMethod", "Density", "IsDeleted")
                        .HasDatabaseName("ix_content_boundaries_method_density_deleted");

                    b.ToTable("content_boundaries", (string)null);
                });

            modelBuilder.Entity("Hartonomous.Core.Domain.Entities.ContentIngestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<int>("ConstantCount")
                        .HasColumnType("integer")
                        .HasColumnName("constant_count");

                    b.PrimitiveCollection<List<Guid>>("ConstantIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<byte[]>("ContentHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("content_hash");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by");

                    b.Property<double>("DeduplicationRatio")
                        .HasColumnType("double precision")
                        .HasColumnName("deduplication_ratio");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("deleted_by");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<DateTime?>("FailedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsSuccessful")
                        .HasColumnType("boolean")
                        .HasColumnName("is_successful");

                    b.Property<string>("Metadata")
                        .HasColumnType("text");

                    b.Property<long>("OriginalSize")
                        .HasColumnType("bigint")
                        .HasColumnName("original_size");

                    b.Property<long>("ProcessingTimeMs")
                        .HasColumnType("bigint")
                        .HasColumnName("processing_time_ms");

                    b.Property<string>("SourceIdentifier")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("source_identifier");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("UniqueConstantCount")
                        .HasColumnType("integer")
                        .HasColumnName("unique_constant_count");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash")
                        .HasDatabaseName("ix_content_ingestions_content_hash");

                    b.HasIndex("ContentType")
                        .HasDatabaseName("ix_content_ingestions_content_type");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_content_ingestions_is_deleted");

                    b.HasIndex("IsSuccessful")
                        .HasDatabaseName("ix_content_ingestions_is_successful");

                    b.HasIndex("SourceIdentifier")
                        .HasDatabaseName("ix_content_ingestions_source_identifier");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("ix_content_ingestions_started_at");

                    b.ToTable("content_ingestions", (string)null);
                });

            modelBuilder.Entity("Hartonomous.Core.Domain.Entities.Embedding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConstantId")
                        .HasColumnType("uuid")
                        .HasColumnName("constant_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("deleted_by");

                    b.Property<int>("Dimensions")
                        .HasColumnType("integer")
                        .HasColumnName("dimensions");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsNormalized")
                        .HasColumnType("boolean")
                        .HasColumnName("is_normalized");

                    b.Property<double>("Magnitude")
                        .HasPrecision(18, 10)
                        .HasColumnType("double precision")
                        .HasColumnName("magnitude");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model_name");

                    b.Property<string>("ModelVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("model_version");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("updated_by");

                    b.Property<MultiPoint>("VectorGeometry")
                        .IsRequired()
                        .HasColumnType("geometry(MultiPointZM, 4326)")
                        .HasColumnName("vector_geometry");

                    b.HasKey("Id");

                    b.HasIndex("ConstantId")
                        .HasDatabaseName("ix_embeddings_constant_id");

                    b.HasIndex("Dimensions")
                        .HasDatabaseName("ix_embeddings_dimensions");

                    b.HasIndex("GeneratedAt")
                        .HasDatabaseName("ix_embeddings_generated_at");

                    b.HasIndex("IsNormalized")
                        .HasDatabaseName("ix_embeddings_is_normalized");

                    b.HasIndex("VectorGeometry")
                        .HasDatabaseName("ix_embeddings_vector_gist");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("VectorGeometry"), "gist");

                    b.HasIndex("ModelName", "ModelVersion")
                        .HasDatabaseName("ix_embeddings_model");

                    b.HasIndex("ConstantId", "ModelName", "IsDeleted")
                        .HasDatabaseName("ix_embeddings_constant_model_deleted");

                    b.ToTable("embeddings", (string)null);
                });

            modelBuilder.Entity("Hartonomous.Core.Domain.Entities.HierarchicalContent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AtomCount")
                        .HasColumnType("integer")
                        .HasColumnName("atom_count");

                    b.Property<Point>("Centroid")
                        .IsRequired()
                        .HasColumnType("geometry(PointZM, 4326)")
                        .HasColumnName("centroid");

                    b.Property<int>("ChildCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("child_count");

                    b.Property<GeometryCollection>("CompleteGeometry")
                        .IsRequired()
                        .HasColumnType("geometry(GeometryCollectionZM, 4326)")
                        .HasColumnName("complete_geometry");

                    b.Property<Guid>("ContentIngestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("content_ingestion_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("deleted_by");

                    b.Property<int>("DescendantCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("descendant_count");

                    b.Property<long?>("EndOffset")
                        .HasColumnType("bigint")
                        .HasColumnName("end_offset");

                    b.Property<int>("HierarchyLevel")
                        .HasColumnType("integer")
                        .HasColumnName("hierarchy_level");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("label");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<long?>("StartOffset")
                        .HasColumnType("bigint")
                        .HasColumnName("start_offset");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("AtomCount")
                        .HasDatabaseName("ix_hierarchical_content_atom_count");

                    b.HasIndex("Centroid")
                        .HasDatabaseName("ix_hierarchical_content_centroid_gist");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Centroid"), "gist");

                    b.HasIndex("CompleteGeometry")
                        .HasDatabaseName("ix_hierarchical_content_geometry_gist");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("CompleteGeometry"), "gist");

                    b.HasIndex("ContentIngestionId")
                        .HasDatabaseName("ix_hierarchical_content_content_ingestion_id");

                    b.HasIndex("DescendantCount")
                        .HasDatabaseName("ix_hierarchical_content_descendant_count");

                    b.HasIndex("HierarchyLevel")
                        .HasDatabaseName("ix_hierarchical_content_hierarchy_level");

                    b.HasIndex("Label")
                        .HasDatabaseName("ix_hierarchical_content_label");

                    b.HasIndex("Metadata")
                        .HasDatabaseName("ix_hierarchical_content_metadata_gin")
                        .HasFilter("metadata IS NOT NULL");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Metadata"), "gin");

                    b.HasIndex("Ordinal")
                        .HasDatabaseName("ix_hierarchical_content_ordinal");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_hierarchical_content_parent_id");

                    b.HasIndex("Title")
                        .HasDatabaseName("ix_hierarchical_content_title")
                        .HasFilter("title IS NOT NULL");

                    b.HasIndex("StartOffset", "EndOffset")
                        .HasDatabaseName("ix_hierarchical_content_offsets")
                        .HasFilter("start_offset IS NOT NULL AND end_offset IS NOT NULL");

                    b.HasIndex("ContentIngestionId", "ParentId", "HierarchyLevel")
                        .HasDatabaseName("ix_hierarchical_content_tree_navigation");

                    b.HasIndex("Label", "HierarchyLevel", "IsDeleted")
                        .HasDatabaseName("ix_hierarchical_content_label_level_deleted");

                    b.HasIndex("ParentId", "Ordinal", "IsDeleted")
                        .HasDatabaseName("ix_hierarchical_content_parent_ordinal_deleted");

                    b.HasIndex("ContentIngestionId", "HierarchyLevel", "Ordinal", "IsDeleted")
                        .HasDatabaseName("ix_hierarchical_content_ingestion_level_ordinal_deleted");

                    b.ToTable("hierarchical_content", (string)null);
                });

            modelBuilder.Entity("Hartonomous.Core.Domain.Entities.Landmark", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("ConstantCount")
                        .HasColumnType("bigint")
                        .HasColumnName("constant_count");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("deleted_by");

                    b.Property<double>("Density")
                        .HasColumnType("double precision")
                        .HasColumnName("density");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<decimal>("HilbertPrefixHigh")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("hilbert_prefix_high");

                    b.Property<decimal>("HilbertPrefixLow")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("hilbert_prefix_low");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("LastStatisticsUpdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_statistics_update");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("ConstantCount")
                        .HasDatabaseName("ix_landmarks_constant_count");

                    b.HasIndex("Density")
                        .HasDatabaseName("ix_landmarks_density");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_landmarks_is_active");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_landmarks_is_deleted");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uq_landmarks_name");

                    b.HasIndex("HilbertPrefixHigh", "HilbertPrefixLow", "Level")
                        .IsUnique()
                        .HasDatabaseName("uq_landmarks_hilbert_tile");

                    b.ToTable("landmarks", (string)null);
                });

            modelBuilder.Entity("Hartonomous.Core.Domain.Entities.NeuralNetworkLayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActivationFunction")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("activation_function");

                    b.Property<LineString>("BiasGeometry")
                        .HasColumnType("geometry(LineStringZM, 4326)")
                        .HasColumnName("bias_geometry");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("deleted_by");

                    b.Property<int?>("Epoch")
                        .HasColumnType("integer")
                        .HasColumnName("epoch");

                    b.Property<string>("InitializationMethod")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("initialization_method");

                    b.Property<int>("InputDim")
                        .HasColumnType("integer")
                        .HasColumnName("input_dim");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsFrozen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_frozen");

                    b.Property<int>("LayerIndex")
                        .HasColumnType("integer")
                        .HasColumnName("layer_index");

                    b.Property<string>("LayerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("layer_name");

                    b.Property<string>("LayerType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Dense")
                        .HasColumnName("layer_type");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("uuid")
                        .HasColumnName("model_id");

                    b.Property<int>("NeuronCount")
                        .HasColumnType("integer")
                        .HasColumnName("neuron_count");

                    b.Property<long>("ParameterCount")
                        .HasColumnType("bigint")
                        .HasColumnName("parameter_count");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("updated_by");

                    b.Property<MultiLineString>("WeightGeometry")
                        .IsRequired()
                        .HasColumnType("geometry(MultiLineStringZM, 4326)")
                        .HasColumnName("weight_geometry");

                    b.Property<double>("WeightNorm")
                        .HasPrecision(18, 10)
                        .HasColumnType("double precision")
                        .HasColumnName("weight_norm");

                    b.HasKey("Id");

                    b.HasIndex("ActivationFunction")
                        .HasDatabaseName("ix_neural_network_layers_activation");

                    b.HasIndex("BiasGeometry")
                        .HasDatabaseName("ix_neural_network_layers_bias_gist");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("BiasGeometry"), "gist");

                    b.HasIndex("Epoch")
                        .HasDatabaseName("ix_neural_network_layers_epoch");

                    b.HasIndex("InputDim")
                        .HasDatabaseName("ix_neural_network_layers_input_dim");

                    b.HasIndex("IsFrozen")
                        .HasDatabaseName("ix_neural_network_layers_is_frozen");

                    b.HasIndex("ModelId")
                        .HasDatabaseName("ix_neural_network_layers_model_id");

                    b.HasIndex("NeuronCount")
                        .HasDatabaseName("ix_neural_network_layers_neuron_count");

                    b.HasIndex("ParameterCount")
                        .HasDatabaseName("ix_neural_network_layers_parameter_count");

                    b.HasIndex("WeightGeometry")
                        .HasDatabaseName("ix_neural_network_layers_weight_gist");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("WeightGeometry"), "gist");

                    b.HasIndex("WeightNorm")
                        .HasDatabaseName("ix_neural_network_layers_weight_norm");

                    b.HasIndex("ModelId", "LayerIndex")
                        .IsUnique()
                        .HasDatabaseName("ix_neural_network_layers_model_index");

                    b.HasIndex("ModelId", "LayerName")
                        .HasDatabaseName("ix_neural_network_layers_model_name");

                    b.HasIndex("LayerType", "ParameterCount", "IsDeleted")
                        .HasDatabaseName("ix_neural_network_layers_type_params_deleted");

                    b.HasIndex("ModelId", "Epoch", "IsDeleted")
                        .HasDatabaseName("ix_neural_network_layers_model_epoch_deleted");

                    b.HasIndex("ModelId", "LayerType", "IsDeleted")
                        .HasDatabaseName("ix_neural_network_layers_model_type_deleted");

                    b.ToTable("neural_network_layers", (string)null);
                });

            modelBuilder.Entity("BPETokenConstant", b =>
                {
                    b.HasOne("Hartonomous.Core.Domain.Entities.BPEToken", null)
                        .WithMany()
                        .HasForeignKey("ComposingTokensId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hartonomous.Core.Domain.Entities.Constant", null)
                        .WithMany()
                        .HasForeignKey("ConstantsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hartonomous.Core.Domain.Entities.Constant", b =>
                {
                    b.HasOne("Hartonomous.Core.Domain.Entities.Landmark", null)
                        .WithMany("Constants")
                        .HasForeignKey("LandmarkId");

                    b.HasOne("Hartonomous.Core.Domain.Entities.Constant", "CanonicalConstant")
                        .WithMany()
                        .HasForeignKey("canonical_constant_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("Hartonomous.Core.Domain.ValueObjects.SpatialCoordinate", "Coordinate", b1 =>
                        {
                            b1.Property<Guid>("ConstantId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("HilbertHigh")
                                .HasColumnType("numeric(20,0)")
                                .HasColumnName("hilbert_high");

                            b1.Property<decimal>("HilbertLow")
                                .HasColumnType("numeric(20,0)")
                                .HasColumnName("hilbert_low");

                            b1.Property<int>("Precision")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(21)
                                .HasColumnName("hilbert_precision");

                            b1.Property<int>("QuantizedCompressibility")
                                .HasColumnType("integer")
                                .HasColumnName("quantized_compressibility")
                                .HasComment("Kolmogorov complexity [0, 2^21-1]: gzip compression ratio");

                            b1.Property<int>("QuantizedConnectivity")
                                .HasColumnType("integer")
                                .HasColumnName("quantized_connectivity")
                                .HasComment("Graph connectivity [0, 2^21-1]: log2(reference_count)");

                            b1.Property<int>("QuantizedEntropy")
                                .HasColumnType("integer")
                                .HasColumnName("quantized_entropy")
                                .HasComment("Shannon entropy [0, 2^21-1]: content randomness");

                            b1.HasKey("ConstantId");

                            b1.HasIndex("QuantizedCompressibility")
                                .HasDatabaseName("ix_constants_compressibility");

                            NpgsqlIndexBuilderExtensions.HasMethod(b1.HasIndex("QuantizedCompressibility"), "btree");

                            b1.HasIndex("QuantizedConnectivity")
                                .HasDatabaseName("ix_constants_connectivity");

                            NpgsqlIndexBuilderExtensions.HasMethod(b1.HasIndex("QuantizedConnectivity"), "btree");

                            b1.HasIndex("QuantizedEntropy")
                                .HasDatabaseName("ix_constants_entropy");

                            NpgsqlIndexBuilderExtensions.HasMethod(b1.HasIndex("QuantizedEntropy"), "btree");

                            b1.HasIndex("HilbertHigh", "HilbertLow")
                                .HasDatabaseName("ix_constants_hilbert4d");

                            NpgsqlIndexBuilderExtensions.HasMethod(b1.HasIndex("HilbertHigh", "HilbertLow"), "btree");

                            b1.HasIndex("QuantizedEntropy", "QuantizedCompressibility", "QuantizedConnectivity")
                                .HasDatabaseName("ix_constants_metadata_composite");

                            NpgsqlIndexBuilderExtensions.HasMethod(b1.HasIndex("QuantizedEntropy", "QuantizedCompressibility", "QuantizedConnectivity"), "btree");

                            b1.ToTable("constants");

                            b1.WithOwner()
                                .HasForeignKey("ConstantId");
                        });

                    b.Navigation("CanonicalConstant");

                    b.Navigation("Coordinate");
                });

            modelBuilder.Entity("Hartonomous.Core.Domain.Entities.ContentBoundary", b =>
                {
                    b.HasOne("Hartonomous.Core.Domain.Entities.ContentIngestion", "ContentIngestion")
                        .WithOne()
                        .HasForeignKey("Hartonomous.Core.Domain.Entities.ContentBoundary", "ContentIngestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Hartonomous.Core.Domain.ValueObjects.BoundingBox4D", "BoundingBox", b1 =>
                        {
                            b1.Property<Guid>("ContentBoundaryId")
                                .HasColumnType("uuid");

                            b1.Property<double>("MaxM")
                                .HasPrecision(18, 6)
                                .HasColumnType("double precision")
                                .HasColumnName("max_m");

                            b1.Property<double>("MaxX")
                                .HasPrecision(18, 6)
                                .HasColumnType("double precision")
                                .HasColumnName("max_x");

                            b1.Property<double>("MaxY")
                                .HasPrecision(18, 6)
                                .HasColumnType("double precision")
                                .HasColumnName("max_y");

                            b1.Property<double>("MaxZ")
                                .HasPrecision(18, 6)
                                .HasColumnType("double precision")
                                .HasColumnName("max_z");

                            b1.Property<double>("MinM")
                                .HasPrecision(18, 6)
                                .HasColumnType("double precision")
                                .HasColumnName("min_m");

                            b1.Property<double>("MinX")
                                .HasPrecision(18, 6)
                                .HasColumnType("double precision")
                                .HasColumnName("min_x");

                            b1.Property<double>("MinY")
                                .HasPrecision(18, 6)
                                .HasColumnType("double precision")
                                .HasColumnName("min_y");

                            b1.Property<double>("MinZ")
                                .HasPrecision(18, 6)
                                .HasColumnType("double precision")
                                .HasColumnName("min_z");

                            b1.HasKey("ContentBoundaryId");

                            b1.HasIndex("MinX", "MaxX", "MinY", "MaxY")
                                .HasDatabaseName("ix_content_boundaries_bbox");

                            b1.ToTable("content_boundaries");

                            b1.WithOwner()
                                .HasForeignKey("ContentBoundaryId");
                        });

                    b.Navigation("BoundingBox")
                        .IsRequired();

                    b.Navigation("ContentIngestion");
                });

            modelBuilder.Entity("Hartonomous.Core.Domain.Entities.Embedding", b =>
                {
                    b.HasOne("Hartonomous.Core.Domain.Entities.Constant", "Constant")
                        .WithMany()
                        .HasForeignKey("ConstantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Constant");
                });

            modelBuilder.Entity("Hartonomous.Core.Domain.Entities.HierarchicalContent", b =>
                {
                    b.HasOne("Hartonomous.Core.Domain.Entities.ContentIngestion", "ContentIngestion")
                        .WithMany()
                        .HasForeignKey("ContentIngestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hartonomous.Core.Domain.Entities.HierarchicalContent", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("Hartonomous.Core.Domain.ValueObjects.BoundingBox4D", "BoundingBox", b1 =>
                        {
                            b1.Property<Guid>("HierarchicalContentId")
                                .HasColumnType("uuid");

                            b1.Property<double>("MaxM")
                                .HasPrecision(18, 6)
                                .HasColumnType("double precision")
                                .HasColumnName("max_m");

                            b1.Property<double>("MaxX")
                                .HasPrecision(18, 6)
                                .HasColumnType("double precision")
                                .HasColumnName("max_x");

                            b1.Property<double>("MaxY")
                                .HasPrecision(18, 6)
                                .HasColumnType("double precision")
                                .HasColumnName("max_y");

                            b1.Property<double>("MaxZ")
                                .HasPrecision(18, 6)
                                .HasColumnType("double precision")
                                .HasColumnName("max_z");

                            b1.Property<double>("MinM")
                                .HasPrecision(18, 6)
                                .HasColumnType("double precision")
                                .HasColumnName("min_m");

                            b1.Property<double>("MinX")
                                .HasPrecision(18, 6)
                                .HasColumnType("double precision")
                                .HasColumnName("min_x");

                            b1.Property<double>("MinY")
                                .HasPrecision(18, 6)
                                .HasColumnType("double precision")
                                .HasColumnName("min_y");

                            b1.Property<double>("MinZ")
                                .HasPrecision(18, 6)
                                .HasColumnType("double precision")
                                .HasColumnName("min_z");

                            b1.HasKey("HierarchicalContentId");

                            b1.HasIndex("MinX", "MaxX", "MinY", "MaxY")
                                .HasDatabaseName("ix_hierarchical_content_bbox");

                            b1.ToTable("hierarchical_content");

                            b1.WithOwner()
                                .HasForeignKey("HierarchicalContentId");
                        });

                    b.Navigation("BoundingBox")
                        .IsRequired();

                    b.Navigation("ContentIngestion");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Hartonomous.Core.Domain.Entities.HierarchicalContent", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Hartonomous.Core.Domain.Entities.Landmark", b =>
                {
                    b.Navigation("Constants");
                });
#pragma warning restore 612, 618
        }
    }
}
