// <auto-generated />
using System;
using System.Collections.Generic;
using Hartonomous.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hartonomous.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "plpython3u");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BPETokenConstant", b =>
                {
                    b.Property<Guid>("ComposingTokensId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConstantsId")
                        .HasColumnType("uuid");

                    b.HasKey("ComposingTokensId", "ConstantsId");

                    b.HasIndex("ConstantsId");

                    b.ToTable("constant_tokens", (string)null);
                });

            modelBuilder.Entity("Hartonomous.Core.Domain.Entities.BPEToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("CompressionRatio")
                        .HasColumnType("double precision");

                    b.PrimitiveCollection<List<Guid>>("ConstantSequence")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("constant_sequence");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("deleted_by");

                    b.Property<long>("Frequency")
                        .HasColumnType("bigint")
                        .HasColumnName("frequency");

                    b.Property<byte[]>("Hash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("hash");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<int>("MergeLevel")
                        .HasColumnType("integer")
                        .HasColumnName("merge_level");

                    b.PrimitiveCollection<List<int>>("ParentTokenIds")
                        .HasColumnType("integer[]");

                    b.Property<int>("SequenceLength")
                        .HasColumnType("integer")
                        .HasColumnName("sequence_length");

                    b.Property<int>("TokenId")
                        .HasColumnType("integer")
                        .HasColumnName("token_id");

                    b.Property<int>("TotalSize")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.Property<long>("VocabularyRank")
                        .HasColumnType("bigint")
                        .HasColumnName("vocabulary_rank");

                    b.HasKey("Id");

                    b.HasIndex("Frequency")
                        .HasDatabaseName("ix_bpe_tokens_frequency");

                    b.HasIndex("Hash")
                        .IsUnique()
                        .HasDatabaseName("ix_bpe_tokens_hash");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_bpe_tokens_is_active");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_bpe_tokens_is_deleted");

                    b.HasIndex("LastUsedAt")
                        .HasDatabaseName("ix_bpe_tokens_last_used");

                    b.HasIndex("MergeLevel")
                        .HasDatabaseName("ix_bpe_tokens_merge_level");

                    b.HasIndex("SequenceLength")
                        .HasDatabaseName("ix_bpe_tokens_sequence_length");

                    b.HasIndex("TokenId")
                        .IsUnique()
                        .HasDatabaseName("ix_bpe_tokens_token_id");

                    b.HasIndex("VocabularyRank")
                        .HasDatabaseName("ix_bpe_tokens_vocabulary_rank");

                    b.ToTable("bpe_tokens", (string)null);
                });

            modelBuilder.Entity("Hartonomous.Core.Domain.Entities.Constant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activated_at");

                    b.Property<Guid?>("CanonicalConstantId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("data");

                    b.Property<DateTime?>("DeduplicatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deduplicated_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("deleted_by");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Frequency")
                        .HasColumnType("bigint")
                        .HasColumnName("frequency");

                    b.Property<byte[]>("Hash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("hash");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsDuplicate")
                        .HasColumnType("boolean")
                        .HasColumnName("is_duplicate");

                    b.Property<Guid?>("LandmarkId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastAccessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_accessed_at");

                    b.Property<Point>("Location")
                        .HasColumnType("geometry(PointZ)")
                        .HasColumnName("location");

                    b.Property<DateTime?>("ProjectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("projected_at");

                    b.Property<long>("ReferenceCount")
                        .HasColumnType("bigint")
                        .HasColumnName("reference_count");

                    b.Property<int>("Size")
                        .HasColumnType("integer")
                        .HasColumnName("size");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("updated_by");

                    b.Property<Guid?>("canonical_constant_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Frequency")
                        .HasDatabaseName("ix_constants_frequency");

                    b.HasIndex("Hash")
                        .IsUnique()
                        .HasDatabaseName("ix_constants_hash");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_constants_is_deleted");

                    b.HasIndex("LandmarkId");

                    b.HasIndex("LastAccessedAt")
                        .HasDatabaseName("ix_constants_last_accessed");

                    b.HasIndex("Location")
                        .HasDatabaseName("ix_constants_location_spatial");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_constants_status");

                    b.HasIndex("canonical_constant_id");

                    b.ToTable("constants", (string)null);
                });

            modelBuilder.Entity("Hartonomous.Core.Domain.Entities.ContentIngestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<int>("ConstantCount")
                        .HasColumnType("integer")
                        .HasColumnName("constant_count");

                    b.PrimitiveCollection<List<Guid>>("ConstantIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<byte[]>("ContentHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("content_hash");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by");

                    b.Property<double>("DeduplicationRatio")
                        .HasColumnType("double precision")
                        .HasColumnName("deduplication_ratio");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("deleted_by");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<DateTime?>("FailedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsSuccessful")
                        .HasColumnType("boolean")
                        .HasColumnName("is_successful");

                    b.Property<string>("Metadata")
                        .HasColumnType("text");

                    b.Property<long>("OriginalSize")
                        .HasColumnType("bigint")
                        .HasColumnName("original_size");

                    b.Property<long>("ProcessingTimeMs")
                        .HasColumnType("bigint")
                        .HasColumnName("processing_time_ms");

                    b.Property<string>("SourceIdentifier")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("source_identifier");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("UniqueConstantCount")
                        .HasColumnType("integer")
                        .HasColumnName("unique_constant_count");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash")
                        .HasDatabaseName("ix_content_ingestions_content_hash");

                    b.HasIndex("ContentType")
                        .HasDatabaseName("ix_content_ingestions_content_type");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_content_ingestions_is_deleted");

                    b.HasIndex("IsSuccessful")
                        .HasDatabaseName("ix_content_ingestions_is_successful");

                    b.HasIndex("SourceIdentifier")
                        .HasDatabaseName("ix_content_ingestions_source_identifier");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("ix_content_ingestions_started_at");

                    b.ToTable("content_ingestions", (string)null);
                });

            modelBuilder.Entity("Hartonomous.Core.Domain.Entities.Landmark", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AverageDistance")
                        .HasColumnType("double precision");

                    b.Property<long>("ConstantCount")
                        .HasColumnType("bigint")
                        .HasColumnName("constant_count");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("deleted_by");

                    b.Property<double>("Density")
                        .HasColumnType("double precision")
                        .HasColumnName("density");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("LastStatisticsUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry(PointZ)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<double>("Radius")
                        .HasColumnType("double precision")
                        .HasColumnName("radius");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("ConstantCount")
                        .HasDatabaseName("ix_landmarks_constant_count");

                    b.HasIndex("Density")
                        .HasDatabaseName("ix_landmarks_density");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_landmarks_is_active");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("ix_landmarks_is_deleted");

                    b.HasIndex("Location")
                        .HasDatabaseName("ix_landmarks_location_spatial");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_landmarks_name");

                    b.HasIndex("Radius")
                        .HasDatabaseName("ix_landmarks_radius");

                    b.ToTable("landmarks", (string)null);
                });

            modelBuilder.Entity("BPETokenConstant", b =>
                {
                    b.HasOne("Hartonomous.Core.Domain.Entities.BPEToken", null)
                        .WithMany()
                        .HasForeignKey("ComposingTokensId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hartonomous.Core.Domain.Entities.Constant", null)
                        .WithMany()
                        .HasForeignKey("ConstantsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hartonomous.Core.Domain.Entities.Constant", b =>
                {
                    b.HasOne("Hartonomous.Core.Domain.Entities.Landmark", null)
                        .WithMany("Constants")
                        .HasForeignKey("LandmarkId");

                    b.HasOne("Hartonomous.Core.Domain.Entities.Constant", "CanonicalConstant")
                        .WithMany()
                        .HasForeignKey("canonical_constant_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("Hartonomous.Core.Domain.ValueObjects.SpatialCoordinate", "Coordinate", b1 =>
                        {
                            b1.Property<Guid>("ConstantId")
                                .HasColumnType("uuid");

                            b1.Property<long>("HilbertIndex")
                                .HasColumnType("bigint")
                                .HasColumnName("hilbert_index");

                            b1.Property<int>("Precision")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(21)
                                .HasColumnName("hilbert_precision");

                            b1.Property<double>("X")
                                .HasColumnType("double precision")
                                .HasColumnName("coordinate_x");

                            b1.Property<double>("Y")
                                .HasColumnType("double precision")
                                .HasColumnName("coordinate_y");

                            b1.Property<double>("Z")
                                .HasColumnType("double precision")
                                .HasColumnName("coordinate_z");

                            b1.HasKey("ConstantId");

                            b1.HasIndex("HilbertIndex")
                                .HasDatabaseName("ix_constants_hilbert_index");

                            NpgsqlIndexBuilderExtensions.HasMethod(b1.HasIndex("HilbertIndex"), "btree");

                            b1.ToTable("constants");

                            b1.WithOwner()
                                .HasForeignKey("ConstantId");
                        });

                    b.Navigation("CanonicalConstant");

                    b.Navigation("Coordinate");
                });

            modelBuilder.Entity("Hartonomous.Core.Domain.Entities.Landmark", b =>
                {
                    b.OwnsOne("Hartonomous.Core.Domain.ValueObjects.SpatialCoordinate", "Center", b1 =>
                        {
                            b1.Property<Guid>("LandmarkId")
                                .HasColumnType("uuid");

                            b1.Property<long>("HilbertIndex")
                                .HasColumnType("bigint")
                                .HasColumnName("center_hilbert_index");

                            b1.Property<int>("Precision")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(21)
                                .HasColumnName("center_hilbert_precision");

                            b1.Property<double>("X")
                                .HasColumnType("double precision")
                                .HasColumnName("center_x");

                            b1.Property<double>("Y")
                                .HasColumnType("double precision")
                                .HasColumnName("center_y");

                            b1.Property<double>("Z")
                                .HasColumnType("double precision")
                                .HasColumnName("center_z");

                            b1.HasKey("LandmarkId");

                            b1.HasIndex("HilbertIndex")
                                .HasDatabaseName("ix_landmarks_center_hilbert_index");

                            NpgsqlIndexBuilderExtensions.HasMethod(b1.HasIndex("HilbertIndex"), "btree");

                            b1.ToTable("landmarks");

                            b1.WithOwner()
                                .HasForeignKey("LandmarkId");
                        });

                    b.Navigation("Center")
                        .IsRequired();
                });

            modelBuilder.Entity("Hartonomous.Core.Domain.Entities.Landmark", b =>
                {
                    b.Navigation("Constants");
                });
#pragma warning restore 612, 618
        }
    }
}
