-- ==============================================================================
-- REMOVED: Old S³ normalization trigger for atoms table
-- ==============================================================================
--
-- The new schema uses Physicality table with GEOMETRY(POINTZM, 0) and has
-- its own check constraint: Physicality_Centroid_Normalized
--
-- This file is kept for reference but contains no active functions.
