using Hartonomous.Core.Domain.Entities;
using NetTopologySuite.Geometries;

namespace Hartonomous.Core.Application.Interfaces;

/// <summary>
/// Repository interface for Embedding entity with spatial query support
/// </summary>
public interface IEmbeddingRepository : IRepository<Embedding>
{
    /// <summary>
    /// Find k nearest embeddings by vector similarity (k-NN query)
    /// </summary>
    /// <param name="targetGeometry">Target embedding's vector geometry</param>
    /// <param name="k">Number of nearest neighbors to return</param>
    /// <param name="modelName">Optional model name filter</param>
    /// <param name="cancellationToken">Cancellation token</param>
    /// <returns>List of k nearest embeddings ordered by distance</returns>
    Task<List<Embedding>> FindNearestAsync(
        MultiPoint targetGeometry,
        int k,
        string? modelName = null,
        CancellationToken cancellationToken = default);
    
    /// <summary>
    /// Find embeddings within distance threshold
    /// </summary>
    Task<List<Embedding>> FindWithinDistanceAsync(
        MultiPoint targetGeometry,
        double maxDistance,
        string? modelName = null,
        CancellationToken cancellationToken = default);
    
    /// <summary>
    /// Get embedding by constant ID and model
    /// </summary>
    Task<Embedding?> GetByConstantAndModelAsync(
        Guid constantId,
        string modelName,
        string? modelVersion = null,
        CancellationToken cancellationToken = default);
    
    /// <summary>
    /// Get all embeddings for a constant (across different models)
    /// </summary>
    Task<List<Embedding>> GetByConstantIdAsync(
        Guid constantId,
        CancellationToken cancellationToken = default);
    
    /// <summary>
    /// Get all embeddings generated by a specific model
    /// </summary>
    Task<List<Embedding>> GetByModelAsync(
        string modelName,
        string? modelVersion = null,
        int? maxResults = null,
        CancellationToken cancellationToken = default);
    
    /// <summary>
    /// Get embeddings by dimensionality
    /// </summary>
    Task<List<Embedding>> GetByDimensionsAsync(
        int dimensions,
        CancellationToken cancellationToken = default);
    
    /// <summary>
    /// Get normalized embeddings only
    /// </summary>
    Task<List<Embedding>> GetNormalizedAsync(
        string? modelName = null,
        CancellationToken cancellationToken = default);
}
