name: CD - Deploy to Development

on:
  push:
    branches: [develop]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  actions: write

env:
  DEPLOYMENT_ENVIRONMENT: development
  DEPLOYMENT_TARGET: HART-DESKTOP

jobs:
  deploy:
    name: Deploy to Development
    uses: ./.github/workflows/cd-deploy-environment.yml
    with:
      environment: development
      git_ref: ${{ github.sha }}
      skip_tests: false
    secrets: inherit
